name: Auto Approval for Dev-Main Syncing PRs

on:
  push:
    branches:
      - main
      - dev

jobs:
  call-workflow:
    uses: jeri-affabv/playground-workflows/.github/workflows/auto-approve-sync-pr.yml@main
    
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}